development:
  adapter: mysql2
  encoding: utf8
  database: service_manager_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: service_manager_test
  pool: 5
  username: root
  password:
